version: 2.1

jobs:
  parallel-job-1:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0 #this job exited successfully
  parallel-job-2:
    docker:
      - image: circleci/node
    steps:
      - run: exit 1 #this job failed
    when:
      condition: on_fail
      steps:
        - run: echo "failed intentionally"
  exit-workflow-job:
    docker:
      - image: circleci/node
  continue-workflow-job:
    docker:
      - image: circleci/node
    steps:
      - run: echo "passed parallel jobs and continued this workflow"

workflows:
  version: 2
  run-parallel-jobs:
    jobs:
      - parallel-job-1
      - parallel-job-2
      - continue-workflow-job:
          requires:
            - parallel-job-1
            - parallel-job-2
