version: 2.1

jobs:
  parallel-job-1:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0 #this job exited successfully
  parallel-job-2: # build step
    machine: true
    steps:
      - checkout
#      - run: echo "$DOCKER_USER"
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t annacircleci/remotecachedemo:uniqueid-builder .
      - run: docker push annacircleci/remotecachedemo:uniqueid-builder
  continue-workflow-job:
    docker:
      - image: circleci/node
    steps:
      - run: echo "passed parallel jobs" # continue the workflow from here

workflows:
  version: 2
  run-parallel-jobs:
    jobs:
      - parallel-job-1
      - parallel-job-2:
          context: remotecachedemo
      - continue-workflow-job:
          requires:
            - parallel-job-1
            - parallel-job-2
