version: 2.1

jobs:
  parallel-job-1:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0 #this job exited successfully
  parallel-job-2:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0 #this job failed
  exit-workflow-job:
    docker:
      - image: circleci/node
    steps:
      - run: echo "passed parallel jobs and continued this workflow"

workflows:
  version: 2
  run-parallel-jobs:
    jobs:
      - parallel-job-1
      - parallel-job-2
      - exit-workflow-job
          requires:
            - parallel-job-0
            - parallel-job-1
